# @format

name: Docker Image Build & Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build worker image
        run: docker build ./worker --file Dockerfile --tag my-image-name:$(date +%s)
      - name: build client image
        run: docker build ./client --file Dockerfile --tag my-image-name:$(date +%s)
      - name: build server image
        run: docker build ./server --file Dockerfile --tag my-image-name:$(date +%s)
