# @format

name: Docker Image Build & Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build worker image
        run: docker build -t hamzazahid/multi-worker:$(date +%s) -f ./worker/Dockerfile ./worker
      - name: build client image
        run: docker build -t hamzazahid/multi-client:$(date +%s) -f ./client/Dockerfile ./client
      - name: build server image
        run: docker build -t hamzazahid/multi-server:$(date +%s) -f ./server/Dockerfile ./server
