# @format

name: Docker Image Build & Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build worker image
        run: ls ./worker/ | less
