# @format

name: k8s deployment
on: [push]
jobs:
  build-app:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: check folders
        run: ls -la | less
      - name: print hello
        run: echo "Hello World!"
